/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static String healthCheck() {
        return "Project Atlas is running";
    }

    public static void main(String[] args) {
        System.out.println(healthCheck());
    }
}
