/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void healthCheckTest() {
        assertEquals("Project Atlas is running", App.healthCheck());
    }
}